# SPDX-FileCopyrightText: 2026 ssocks contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1

[[annotations]]
path = [
  "LICENSE-APACHE",
  "LICENSE-MIT",
  ".release-please-manifest.json",
  "release-please-config.json",
  "VERSION",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 ssocks contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["vectors/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 ssocks contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"
